name: merge-release-pr-to-main

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number to merge
        required: true

jobs:
  merge-release-to-main:
    runs-on: ubuntu-20.04
    steps:
      # - name: enable merge commits
      #   uses: octokit/request-action@v2.x
      #   with:
      #     route: PATCH /repos/{owner}/{repo}
      #     owner: insignias
      #     repo: React
      #     allow_merge_commit: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

      - name: merge release branch pr to main
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/{owner}/{repo}/pulls/{pull_number}/merge
          owner: insignias
          repo: React
          pull_number: ${{ inputs.pr_number }}
          merge_method: 'merge'
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

      # - name: disable merge commits
      #   uses: octokit/request-action@v2.x
      #   with:
      #     route: PATCH /repos/{owner}/{repo}
      #     owner: insignias
      #     repo: React
      #     allow_merge_commit: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
  