name: merge-release-pr-to-main

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number to merge
        required: true

jobs:
  merge-release-to-main:
    if: contains(github.ref_name, 'gh-workflow')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions-cool/check-user-permission@v2
        id: check
        with:
          require: 'admin'
          username: ${{ github.triggering_actor }}

      - name: check if PR source is a release branch
        if: steps.check.outputs.require-result
        id: check_source
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}
          owner: insignias
          repo: React
          pull_number: ${{ inputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
      
      - run: echo ${{ steps.check_source.outputs.head.ref }}

      - name: enable merge commits
        if: steps.check.outputs.require-result && startsWith(steps.check_source.outputs.head.ref, 'release/')
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}
          owner: insignias
          repo: React
          allow_merge_commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

      - name: merge release branch pr to main
        if: steps.check.outputs.require-result && startsWith(steps.check_source.outputs.head.ref, 'release/')
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/{owner}/{repo}/pulls/{pull_number}/merge
          owner: insignias
          repo: React
          pull_number: ${{ inputs.pr_number }}
          merge_method: 'merge'
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

      - name: disable merge commits
        if: steps.check.outputs.require-result && startsWith(steps.check_source.outputs.head.ref, 'release/')
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}
          owner: insignias
          repo: React
          allow_merge_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
  